import type { Metadata } from "next";
import azureGray from "../../public/azure-gray.svg";
import "./globals.css";
import QueryProvider from "@/provider/QueryProvider";
import { Toaster } from "sonner";
import { Space_Grotesk } from "next/font/google";
import Image from "next/image";
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  style: "normal",
  weight: ["500"],
});
export const metadata: Metadata = {
  title: "Azure Seminar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background:
            'linear-gradient(to left, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url("/main-background.svg") no-repeat center',
          backgroundSize: "cover",
        }}
        className={`${spaceGrotesk.className} antialiased h-screen w-full relative`}
      >
        {/* <Image
          src={azureGray}
          className="pointer-events-none user-select-none absolute top-3 left-3 opacity-40"
          width={200}
          height={200}
          alt="azure-gray"
          priority
        /> */}
        <Toaster richColors position="top-center" />
        <QueryProvider> {children}</QueryProvider>
      </body>
    </html>
  );
}
